### ISSUE TITLE
Import from an archived resource datapackage interaction is failing

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2292]
Creating a new resource from a datapackage of interaction type does not work properly an shows this error:

<img width="1311" alt="image" src="https://github.com/gbif/ipt/assets/63795703/7188c587-511f-4e24-854f-11e8697c3768">

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue.
Yes, it can be, I didn't test that functionality for new data packages Interaction DP and Material DP (it's stable for camtraps only). I'll see whether it's easy to fix

**Comment by mike-podolskiy90** [comment]
I've fixed this, will deploy shortly

**Comment by EstebanMH-SiB** [comment]
Thank you very much @mike-podolskiy90, it creates a new resource but without uploading the metadata: 
![image](https://github.com/gbif/ipt/assets/63795703/7a8eebdd-0222-4195-a230-7343a9d5550b)

Also metadata profile for Interaction is still not working properly, in never saves the contributors and only have one section instead of several like camtrapDP, we did a test in a 3.0.3 version:
![image](https://github.com/gbif/ipt/assets/63795703/6d95a834-1152-4716-8aa1-260e7d030a1e)

**Comment by mike-podolskiy90** [comment]
As far as I remember metadata is not quite decided yet for the interaction dp, so it displays a bare minimum. I'll have a look
